version: "3.8"

services:
  facerecognition:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: facerecognition-api
    ports:
      - "3000:3000"
    volumes:
      - people_data:/app/people
      - logs_data:/app/logs
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

volumes:
  people_data:
    driver: local
  logs_data:
    driver: local
